services:
  upload.annotation_reader:
    class: Trustylabs\UploadBundle\Annotation\UploadAnnotationReader
    arguments: ["@annotations.reader"]
  upload.handler:
    class: Trustylabs\UploadBundle\Handler\UploadHandler
  upload.subsriber:
    class: Trustylabs\UploadBundle\Listener\UploadSubscriber
    arguments: ["@upload.annotation_reader","@upload.handler"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }